version: 2
jobs:
  build:
    macos:
      xcode: "9.4.1"
    working_directory: /Users/distiller/project
    steps:
      - checkout
      - run:
          working_directory: ~/project/macos
          command: ./build-cef-mac.sh